### ISSUE TITLE
Support Iowa State Bufkit Archive

### ISSUE THREAD

**Issue by akrherz** [kylejgillett/sounderpy#1]
Congrats on your library :)  Just wanted to drop a suggestion about supporting the bufkit archive I maintain.  There's massive per UTC date archives like so, back a number of years.

https://mtarchive.geol.iastate.edu/2023/07/17/bufkit/

I do have some crude [web services](https://mesonet.agron.iastate.edu/api/1/docs#/nws/service_nws_bufkit__fmt__get) for more programmatic access to the archive.

Happy to address any questions / problems you encounter.  Thanks for the consideration.

**Comment by kylejgillett** [comment]
This is an excellent idea! I will have to take a look into the data access process, but this seems totally plausible. I will attempt to work this into a future release! 

Thanks for the idea!

**Comment by kylejgillett** [comment]
Access to IEM's massive BUFKIT archive has been added to the next release of SounderPy!

Thanks for the suggestion!
