### ISSUE TITLE
Add functionality to use WMO ID on get_obs_data() function

### ISSUE THREAD

**Issue by AstroCGHA** [kylejgillett/sounderpy#11]
Greetings! In the RAOB_STATIONS.txt file, there are many stations that do not have an ICAO ID e.g. Tanay, Ph. Station etc. Even with 'editing' and adding a 'substitute' ICAO ID for a certain station doesn't seem to work for querying the sounding profile of interest.

For the `get_obs_data()` function, an alternative way I suggest is to have an option for the user to either input/use;

1.  If available, the station's corresponding ICAO ID (3 or 4 letters; DTX or KDTX) or
2.  If ICAO ID is not available, the station's corresponding WMO ID instead (5 digit code; 72632)

Congrats on this work of yours. And thanks for consideration. :)

**Comment by kylejgillett** [comment]
Hey @AstroCGHA! 

This is a great point and a good idea. Not sure why consideration escaped my mind originally lol

I will add this to the next release of SounderPy which I will have published this month!

**Comment by kylejgillett** [comment]
Thank you for submitting this issue (idea)! 

Requesting RAOB data by WMO ID has been added to SounderPy's get_obs_data() function.
Requesting RAOB site lat/lon by WMO ID has been added to SounderPy's raob_latlon() function. 

These updates will be available with the next release of SounderPy.
