### ISSUE TITLE
Support for NCEP FNL gridded dataset access

### ISSUE THREAD

**Issue by AstroCGHA** [kylejgillett/sounderpy#12]
Aside from the popular ERA5 Reanalysis, another 'reanalysis' dataset that can be used to extract sounding profile and can be added in a possible future work will be the NCEP FNL (1 deg) and/or NCEP-GDAS FNL (0.25 deg, better horizontal resolution than the previous rendition). Sample article that uses the aforementioned dataset is attached [here](https://www.researchgate.net/publication/336038449_The_College_Park_Maryland_Tornado_of_24_September_2001).

I would like to suggest an additional support to the `get_model_data()` function to load and parse data from the NCEP FNL and/or NCEP-GDAS FNL dataset. It is available via RDA's THREDDS Dataserver for [1 deg](https://thredds.rda.ucar.edu/thredds/catalog/files/g/ds083.2/catalog.html) and/or [0.25 deg](https://thredds.rda.ucar.edu/thredds/catalog/catalog_ds083.3.html). 

May help WRF users, as well. Thank you for responding to my previous suggestion and I'm enjoying using your package~

**Comment by kylejgillett** [comment]
Thanks for the idea submission, @AstroCGHA! 

I have added access to this dataset to SounderPy (specifically the 0.25-degree set). I will add that there appears to be some strange behavior at times with MetPy calculations when using this data, but I have yet to discover what the issues are. 

I will make this data access available to the next release of SounderPy and perhaps users can possibly help identify what may be causing these issues. 

Closing this issue for now.
