### ISSUE TITLE
Document conda-forge installation option

### ISSUE THREAD

**Issue by akrherz** [kylejgillett/sounderpy#20]
Greetings, I've created a [sounderpy feedstock](https://github.com/conda-forge/sounderpy-feedstock) for conda-forge.  So conda-forge users can now install sounderpy via

> conda -c conda-forge install sounderpy

It may be nice to document this within your README, etc...

**Comment by kylejgillett** [comment]
> Greetings, I've created a [sounderpy feedstock](https://github.com/conda-forge/sounderpy-feedstock) for conda-forge.  So conda-forge users can now install sounderpy via
> 
> > conda -c conda-forge install sounderpy
> 
> It may be nice to document this within your README, etc...
> 

Hi Daryl! 

This is epic, thanks for taking the time to do this! I always wanted to eventually do this but never got around to it. 

Much appreciated!

**Comment by kylejgillett** [comment]
Documentation for the feedstock has been added to the README and the docs for the next release.
