### ISSUE TITLE
Improve Sounding Plot Functions 

### ISSUE THREAD

**Issue by ethankerrwx** [kylejgillett/sounderpy#3]
I first want to say that I have very limited experience working with packages. I've only used python for statisitcs/data analysis before, so I've only ever intalled pandas, numpy, seaborn, etc, and called it a day. However, sounderpy looks awesome so I'm trying to install it.

When installing sounderpy, this error message appears:

ERROR: Could not find a version that satisfies the requirement sounderpy
ERROR: No matching distribution found for sounderpy

I don't know if this is something trivial or not, but I couldn't really find any online help of where to go from here.

Thanks!

**Comment by kylejgillett** [comment]
Thanks for reaching out! Glad you would like to use SounderPy. 

Do you know what version of Python you have? SounderPy requires Python 3.10 or greater.

**Comment by ethankerrwx** [comment]
Hmmm, that could have been the problem. It’s been a while since I ran up
Python on my computer so I’ll have to check it out. Thanks!

**Comment by kylejgillett** [comment]
Awesome, let me know if that works!

**Comment by ethankerrwx** [comment]
Good evening,

Apologies for taking so long to respond. I just got back to trying this
again, and this time it worked! When I previously tried, I did it on a
Jupyter Notebook and ran into trouble. I've been switching my Python
operations over to PyCharm and installing it there was a piece of cake!
When I generate a sounding, some of the wording and information seems more
cluttered than it should be and overlaps. How would I fix that?

Thanks,
Ethan Kerr
[image: image.png]

**Comment by kylejgillett** [comment]
Glad you got it working! 

As to the plot titles: yes that is something I have realized to be a bit of an issue with specific models; that not everything fits in the title line like it should. The fix in that regard lies within the source code. One option you may consider is creating a plot yourself using MetPy's plotting functions examples. I am working on a new MetPy sounding plot example that can be found here: https://github.com/Unidata/MetPy/issues/2460#issuecomment-1661174128. 

You should be able to rather easily convert this example into one that works with SounderPy data. For example, this section of code in the MetPy example that gets observed data:

```
col_names = ['pressure', 'height', 'temperature', 'dewpoint', 'direction', 'speed']

df = pd.read_fwf(get_test_data('may4_sounding.txt', as_file_obj=False),
                 skiprows=5, usecols=[0, 1, 2, 3, 6, 7], names=col_names)

# Drop any rows with all NaN values for T, Td, winds
df = df.dropna(subset=('temperature', 'dewpoint', 'direction', 'speed'
                       ), how='all').reset_index(drop=True)

p = df['pressure'].values * units.hPa
T = df['temperature'].values * units.degC
Td = df['dewpoint'].values * units.degC
wind_speed = df['speed'].values * units.knots
wind_dir = df['direction'].values * units.degrees
u, v = mpcalc.wind_components(wind_speed, wind_dir)

```

could be converted too:

```
clean_data = spy.get_bufkit_data('HRRR', 'KMOP', 0)

p = clean_data['p']
T = clean_data['T']
Td = clean_data['Td']
u = clean_data['u']
v  = clean_data['v']

```

then, after applying the actual plot code that I provide in that MetPy issue, you could make something like this: 

My eventual plan is to implement a more advanced plot much like the one below into SounderPy. Hopefully that is soon!

![255392709-a56a2fdb-dd10-4513-aaf9-9fdc204369b0](https://github.com/kylejgillett/sounderpy/assets/100786530/f948513f-7176-4d36-8aa9-c8399c7983a5)

**Comment by ethankerrwx** [comment]
Alright, that sounds easy enough. Thank you!

**Comment by kylejgillett** [comment]
Improved plotting functions for both the Skew-T and hodograph have been developed and will be implemented into the next release of SounderPy.

Here is an example of the new plot: 
![NEW-HODO-EXAMPLE](https://github.com/kylejgillett/sounderpy/assets/100786530/53a9355b-fe05-4e71-8b3c-3a86fb2be251)

![NEW-SKEW-EXAMPLE](https://github.com/kylejgillett/sounderpy/assets/100786530/fc043f79-48c0-47cd-81b3-859e861485c4)

**Comment by ethankerrwx** [comment]
Good evening,

I've been using Sounderpy lately, and I'm getting a better hang of things. I love how easy and quick it is to make a sounding. My only issue is that I still can't figure out for the life of me how to prevent all the text from being jumbled up. Any suggestions?

Thanks,
Ethan Kerr

![image](https://github.com/kylejgillett/sounderpy/assets/140041545/acbe7e90-7a2a-457b-b6db-03f3c3bbb76c)

**Comment by ethankerrwx** [comment]
Hold up, I literally just came across a tweet that answered my question. That's kind of crazy. Thanks for answering my question via some random tweet!

**Comment by kylejgillett** [comment]
hey @ethankerrwx !

Thanks again for using SounderPy -- I love that so many folks are finding it useful! 

I am glad you came across that tweet haha! It turns out that displaying the plot inline can cause some formatting issues on smaller screens.  

In case anyone comes across this in the future, the fix for this issue will be saving the plot to a file -- then the dimensions and formatting will be correct. 

use the `method='save'` kwarg:

`metpy_sounding(clean_data, method='save', filename="some_filename")`
