### ISSUE TITLE
Bug importing the library

### ISSUE THREAD

**Issue by anadape** [kylejgillett/sounderpy#30]
I am trying to run sounderpy in colab, specifically the notebook "beginners_sounderpy_cookbook.ipynb". I run:

!pip install sounderpy

and when I run the second line: "import sounderpy as spy", I get the following error:

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-39-c6222062ce51>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import sounderpy as spy

12 frames

[/usr/lib/python3.10/dataclasses.py](https://localhost:8080/#) in _process_class(cls, init, repr, eq, order, unsafe_hash, frozen, match_args, kw_only, slots)
    988         # Raise an exception if we're frozen, but none of our bases are.
    989         if not any_frozen_base and frozen:
--> 990             raise TypeError('cannot inherit frozen dataclass from a '
    991                             'non-frozen one')
    992 

TypeError: cannot inherit frozen dataclass from a non-frozen one

I've tried several things but I cannot find any solution. Has this happened to someone else? or would you have an idea of how to solve it? Thank you in advance.

**Comment by kylejgillett** [comment]
Hmmmm, strange. 

This is happening in Google Colabs? I haven't seen this error before. I am away from my computer today, so I wont be able to dig into this for a little bit.

If you are attempting to run the actual cookbook notebook, attempt to create a new blank notebook and try to install and import again. Let me know if you still get the error.

**Comment by anadape** [comment]
Okay, now it works with the new blank notebook. Thank you for your reply
